In [5]:
import dask.dataframe as dd

In [31]:
dtypes = {
    '_3순위납부업종': 'object',
    '_3순위여유업종': 'object',
    '최종카드론_신청경로코드': 'object'
}

df1 = dd.read_csv(
    r'C:\Users\campus4D044\201808_승인매출정보.csv',
    encoding='utf-8',
    dtype=dtypes
)

df1 = df.compute()

MemoryError: Unable to allocate 161. MiB for an array with shape (409, 51704) and data type int64

In [ ]:
columns_list = list(df1.columns)
for col in columns_list:
    print(col)

In [22]:
df2 = pd.read_csv('201808_채널정보.csv', encoding = 'utf-8')

In [23]:
columns_list = list(df2.columns)
for col in columns_list:
    print(col)

기준년월
발급회원번호
인입횟수_ARS_R6M
이용메뉴건수_ARS_R6M
인입일수_ARS_R6M
인입월수_ARS_R6M
인입후경과월_ARS
인입횟수_ARS_B0M
이용메뉴건수_ARS_B0M
인입일수_ARS_B0M
방문횟수_PC_R6M
방문일수_PC_R6M
방문월수_PC_R6M
방문후경과월_PC_R6M
방문횟수_앱_R6M
방문일수_앱_R6M
방문월수_앱_R6M
방문후경과월_앱_R6M
방문횟수_모바일웹_R6M
방문일수_모바일웹_R6M
방문월수_모바일웹_R6M
방문후경과월_모바일웹_R6M
방문횟수_PC_B0M
방문일수_PC_B0M
방문횟수_앱_B0M
방문일수_앱_B0M
방문횟수_모바일웹_B0M
방문일수_모바일웹_B0M
인입횟수_IB_R6M
인입횟수_금융_IB_R6M
인입일수_IB_R6M
인입월수_IB_R6M
이용메뉴건수_IB_R6M
인입후경과월_IB_R6M
인입횟수_IB_B0M
인입일수_IB_B0M
이용메뉴건수_IB_B0M
인입불만횟수_IB_R6M
인입불만일수_IB_R6M
인입불만월수_IB_R6M
인입불만후경과월_IB_R6M
인입불만횟수_IB_B0M
인입불만일수_IB_B0M
상담건수_B0M
IB문의건수_사용승인내역_B0M
IB문의건수_한도_B0M
IB문의건수_선결제_B0M
IB문의건수_결제_B0M
IB문의건수_할부_B0M
IB문의건수_정보변경_B0M
IB문의건수_결제일변경_B0M
IB문의건수_명세서_B0M
IB문의건수_비밀번호_B0M
IB문의건수_SMS_B0M
IB문의건수_APP_B0M
IB문의건수_부대서비스_B0M
IB문의건수_포인트_B0M
IB문의건수_카드발급_B0M
IB문의건수_BL_B0M
IB문의건수_분실도난_B0M
IB문의건수_CA_B0M
IB문의건수_CL_RV_B0M
IB문의건수_CS_B0M
IB상담건수_VOC_B0M
IB상담건수_VOC민원_B0M
IB상담건수_VOC불만_B0M
IB상담건수_금감원_B0M
상담건수_R6M
IB문의건수_사용승인내역_R6M
IB문의건수_한도_R6M
IB문의건수_선결제_R6M
IB문의건수_결제_R6M
IB문의건수_할부_R6M
IB문의건수_정보변경_R6M
IB문의건수_결제일변경_R6M
IB문의건수_명세서_R6M
IB문의건수_비밀번호_R6M
IB문의건수_SMS_R6M
IB문의건수_APP_R6M
IB문의건수_부대서비스_R6M
IB문의건수_포인트_R6M
IB문의건수_카드발급_R6M
IB문의건수_BL_R6M
IB문의건수_분실도난_R6M
IB문의건수_CA_R6M
IB문의건수_CL_RV_R6M
IB문의건수_CS_R6M
IB상담건수_VOC_R6M
IB상담건수_VOC민원_R6M
IB상담건수_VOC불만_R6M
IB상담건수_금감원_R6M
불만제기건수_B0M
불만제기건수_R12M
불만제기후경과월_R12M
당사PAY_방문횟수_B0M
당사PAY_방문횟수_R6M
당사PAY_방문월수_R6M
당사멤버쉽_방문횟수_B0M
당사멤버쉽_방문횟수_R6M
당사멤버쉽_방문월수_R6M
OS구분코드
홈페이지_금융건수_R6M
홈페이지_선결제건수_R6M
홈페이지_금융건수_R3M
홈페이지_선결제건수_R3M

In [24]:
df3 = pd.read_csv('201808_청구정보.csv', encoding = 'utf-8')

In [25]:
columns_list = list(df3.columns)
for col in columns_list:
    print(col)

기준년월
발급회원번호
대표결제일
대표결제방법코드
대표청구지고객주소구분코드
대표청구서수령지구분코드
청구서수령방법
청구서발송여부_B0
청구서발송여부_R3M
청구서발송여부_R6M
청구금액_B0
청구금액_R3M
청구금액_R6M
포인트_마일리지_건별_B0M
포인트_마일리지_건별_R3M
포인트_포인트_건별_B0M
포인트_포인트_건별_R3M
포인트_마일리지_월적립_B0M
포인트_마일리지_월적립_R3M
포인트_포인트_월적립_B0M
포인트_포인트_월적립_R3M
포인트_적립포인트_R12M
포인트_적립포인트_R3M
포인트_이용포인트_R12M
포인트_이용포인트_R3M
포인트_잔여포인트_B0M
마일_적립포인트_R12M
마일_적립포인트_R3M
마일_이용포인트_R12M
마일_이용포인트_R3M
마일_잔여포인트_B0M
할인건수_R3M
할인금액_R3M
할인건수_B0M
할인금액_B0M
할인금액_청구서_R3M
할인금액_청구서_B0M
상환개월수_결제일_R6M
상환개월수_결제일_R3M
선결제건수_R6M
선결제건수_R3M
연체건수_R6M
연체건수_R3M
혜택수혜금액_R3M
포인트_마일리지_환산_B0M
혜택수혜금액

In [26]:
df4 = pd.read_csv('201808_회원정보.csv', encoding = 'utf-8')

In [27]:
columns_list = list(df4.columns)
for col in columns_list:
    print(col)

기준년월
발급회원번호
남녀구분코드
연령
VIP등급코드
최상위카드등급코드
회원여부_이용가능
회원여부_이용가능_CA
회원여부_이용가능_카드론
소지여부_신용
소지카드수_유효_신용
소지카드수_이용가능_신용
입회일자_신용
입회경과개월수_신용
회원여부_연체
이용거절여부_카드론
동의여부_한도증액안내
수신거부여부_TM
수신거부여부_DM
수신거부여부_메일
수신거부여부_SMS
가입통신회사코드
탈회횟수_누적
최종탈회후경과월
탈회횟수_발급6개월이내
탈회횟수_발급1년이내
거주시도명
직장시도명
마케팅동의여부
유효카드수_신용체크
유효카드수_신용
유효카드수_신용_가족
유효카드수_체크
유효카드수_체크_가족
이용가능카드수_신용체크
이용가능카드수_신용
이용가능카드수_신용_가족
이용가능카드수_체크
이용가능카드수_체크_가족
이용카드수_신용체크
이용카드수_신용
이용카드수_신용_가족
이용카드수_체크
이용카드수_체크_가족
이용금액_R3M_신용체크
이용금액_R3M_신용
이용금액_R3M_신용_가족
이용금액_R3M_체크
이용금액_R3M_체크_가족
_1순위카드이용금액
_1순위카드이용건수
_1순위신용체크구분
_2순위카드이용금액
_2순위카드이용건수
_2순위신용체크구분
최종유효년월_신용_이용가능
최종유효년월_신용_이용
최종카드발급일자
보유여부_해외겸용_본인
이용가능여부_해외겸용_본인
이용여부_3M_해외겸용_본인
보유여부_해외겸용_신용_본인
이용가능여부_해외겸용_신용_본인
이용여부_3M_해외겸용_신용_본인
연회비발생카드수_B0M
연회비할인카드수_B0M
기본연회비_B0M
제휴연회비_B0M
할인금액_기본연회비_B0M
할인금액_제휴연회비_B0M
청구금액_기본연회비_B0M
청구금액_제휴연회비_B0M
상품관련면제카드수_B0M
임직원면제카드수_B0M
우수회원면제카드수_B0M
기타면제카드수_B0M
카드신청건수
Life_Stage
최종카드발급경과월

# 필요한 부분만 불러오기

In [35]:
df3_filtered = df3[[
    '발급회원번호',       
    '청구금액_R3M', 
    '청구금액_R6M', 
    '포인트_적립포인트_R3M', 
    '포인트_적립포인트_R12M',
    '포인트_잔여포인트_B0M',
    '마일_적립포인트_R3M', 
    '마일_잔여포인트_B0M'
]]

df4_filtered = df4[[
    '발급회원번호',       
    '입회경과개월수_신용', 
    '회원여부_이용가능',   
    '연령',          
    '남녀구분코드',  
    'VIP등급코드',   
    '최상위카드등급코드',  
    '유효카드수_신용',  
    '이용금액_R3M_신용',  
    'Life_Stage',    
    '최종카드발급경과월'
]]

merged_data = pd.merge(
    df3_filtered,
    df4_filtered,
    on='발급회원번호',  
    how='inner'       
)

In [36]:
merged_data.to_csv('외부데이터.csv')

,발급회원번호,청구금액_R3M,청구금액_R6M,포인트_적립포인트_R3M,포인트_적립포인트_R12M,포인트_잔여포인트_B0M,마일_적립포인트_R3M,마일_잔여포인트_B0M,입회경과개월수_신용,회원여부_이용가능,연령,남녀구분코드,VIP등급코드,최상위카드등급코드,유효카드수_신용,이용금액_R3M_신용,Life_Stage,최종카드발급경과월
0,SYN_0,5333639,11941906,1651,3641,0,0,0,68,1,40대,2,07,_,1,-119082,5.자녀성장기(2),23
1,SYN_1,919412,1462656,0,0,0,0,0,13,1,30대,1,_,1,1,1313063,4.자녀성장기(1),19
2,SYN_2,362851,713460,0,0,0,0,0,3,1,40대,2,_,_,1,284138,4.자녀성장기(1),6
3,SYN_3,59469,118569,0,0,0,0,0,150,1,40대,1,_,_,2,39611,4.자녀성장기(1),44
4,SYN_4,0,0,0,0,0,0,0,76,0,40대,2,_,_,1,0,5.자녀성장기(2),18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2999995,SYN_2999995,0,0,0,0,0,0,0,78,1,30대,2,_,_,2,0,4.자녀성장기(1),20
2999996,SYN_2999996,4419249,11658518,3597,14884,0,0,0,223,1,50대,1,07,_,2,962655,5.자녀성장기(2),1
2999997,SYN_2999997,2618686,4899362,0,0,0,0,0,11,1,50대,2,_,3,1,2100614,5.자녀성장기(2),16
2999998,SYN_2999998,451203,936826,3584,0,0,0,0,24,1,20대,1,_,_,1,664852,1.Single,1
2999999,SYN_2999999,1073420,3523310,2175,2416,0,0,0,92,1,50대,1,_,_,1,187888,5.자녀성장기(2),40

In [37]:
merged_data.to_csv('외부데이터.csv', index=False, encoding='utf-8-sig')